from django.urls import path

from . import views

urlpatterns = [path("", views.index, name="index"),
               path("index.html", views.index, name="index_html"),
	       path('UserLogin', views.UserLogin, name="UserLogin"),
	       path('UserLoginAction', views.UserLoginAction, name="UserLoginAction"),	
	       path('AdminLogin', views.AdminLogin, name="AdminLogin"),
	       path('AdminLoginAction', views.AdminLoginAction, name="AdminLoginAction"),	
	       path('MunicipalityLogin', views.MunicipalityLogin, name="MunicipalityLogin"),
	       path('MunicipalityLoginAction', views.MunicipalityLoginAction, name="MunicipalityLoginAction"),
	       path('OfficerLogin', views.OfficerLogin, name="OfficerLogin"),
	       path('OfficerLoginAction', views.OfficerLoginAction, name="OfficerLoginAction"),
	       path('Register', views.Register, name="Register"),
	       path('RegisterAction', views.RegisterAction, name="RegisterAction"),
	       path('AddMunicipality', views.AddMunicipality, name="AddMunicipality"),	
	       path('AddMunicipalityAction', views.AddMunicipalityAction, name="AddMunicipalityAction"),
	       path('UpdateMunicipality', views.UpdateMunicipality, name="UpdateMunicipality"),
	       path('UpdateMunicipalityAction', views.UpdateMunicipalityAction, name="UpdateMunicipalityAction"),
	       path('DeleteMunicipality', views.DeleteMunicipality, name="DeleteMunicipality"),
	       path('ViewMunicipality', views.ViewMunicipality, name="ViewMunicipality"),
	       path('ViewUserComplaint', views.ViewUserComplaint, name="ViewUserComplaint"),	       
	       path('ViewCitizens', views.ViewCitizens, name="ViewCitizens"),
	       path('UpdateCitizen', views.UpdateCitizen, name="UpdateCitizen"),
	       path('UpdateCitizenAction', views.UpdateCitizenAction, name="UpdateCitizenAction"),
	       path('DeleteCitizen', views.DeleteCitizen, name="DeleteCitizen"),
	       path('AddOfficer', views.AddOfficer, name="AddOfficer"),
	       path('AddOfficerAction', views.AddOfficerAction, name="AddOfficerAction"),
	       path('ViewOfficer', views.ViewOfficer, name="ViewOfficer"),
	       path('UpdateOfficer', views.UpdateOfficer, name="UpdateOfficer"),
	       path('UpdateOfficerAction', views.UpdateOfficerAction, name="UpdateOfficerAction"),
	       path('DeleteOfficer', views.DeleteOfficer, name="DeleteOfficer"),
	       path('Graph', views.Graph, name="Graph"),
	       path('Broadcast', views.Broadcast, name="Broadcast"),
	       path('BroadcastAction', views.BroadcastAction, name="BroadcastAction"),

	       path('ReportComplaint', views.ReportComplaint, name="ReportComplaint"),	
	       path('ReportComplaintAction', views.ReportComplaintAction, name="ReportComplaintAction"),
	       path('ViewGrievanceStatus', views.ViewGrievanceStatus, name="ViewGrievanceStatus"),	
	       path('DeleteComplaint', views.DeleteComplaint, name="DeleteComplaint"),
	       path('UpdateComplaint', views.UpdateComplaint, name="UpdateComplaint"),
	       path('UpdateComplaintAction', views.UpdateComplaintAction, name="UpdateComplaintAction"),
	       path('ComplaintRequest', views.ComplaintRequest, name="ComplaintRequest"),
	       
	       path('ViewTask', views.ViewTask, name="ViewTask"),
	       path('UpdateStatus', views.UpdateStatus, name="UpdateStatus"),

	       path('AssignedTo', views.AssignedTo, name="AssignedTo"),
	       path('AssignedToAction', views.AssignedToAction, name="AssignedToAction"),
]